version: '3.8'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=123123123
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=project_calendar

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123123
      - POSTGRES_DB=project_calendar
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
